### ISSUE TITLE
Add link to /news

### ISSUE THREAD

**Issue by JohnVeness** [kaitai-io/kaitai-io.github.io#16]
I didn't even realise there was a /news folder until I clicked on the 0.9 announcement and hand-manipulated the URL! I think it would be good to have a link to the news index in the top menu.

As a secondary request it would be nice to pretty up the news index, e.g. adding extracts of each post, dates etc. And an RSS feed.

**Comment by pfroud** [comment]
I opened three pull requests to add a link to the news page into the nav bar:

* https://github.com/kaitai-io/kaitai-io.github.io/pull/21
* https://github.com/kaitai-io/kaitai_struct_doc/pull/51
* ~~https://github.com/kaitai-io/formats-kaitai-io.github.io/pull/1~~
* https://github.com/kaitai-io/kaitai_struct_formats/pull/655

**Comment by pfroud** [comment]
The public website now has a link to the news page! Here is what it looks like:

![Screenshot of Kaitai Struct homepage](https://user-images.githubusercontent.com/9056906/227663895-03507f54-3020-4253-9c19-8985ecfb47cc.png)


![Screenshot of Kaitai Struct format gallery](https://user-images.githubusercontent.com/9056906/227663912-07199fc1-da9c-4839-b038-99cf7b058ab2.png)

![Screenshot of Kaitai Struct documentation webpage](https://user-images.githubusercontent.com/9056906/227663930-a749ae63-2274-42cb-a3c4-4b4b743773e5.png)

**Comment by generalmimon** [comment]
This is now finished thanks to @pfroud, closing.
