### ISSUE TITLE
Add OWASP ZAP to "Built with Kaitai Struct"

### ISSUE THREAD

**Issue by SkypLabs** [kaitai-io/kaitai-io.github.io#23]
Hi,

The [OWASP ZAP](https://www.zaproxy.org/) project is now using Kaitai Struct to parse macOS `.DS_Store` files following my contributions to both projects (https://github.com/kaitai-io/kaitai_struct_formats/pull/131 and https://github.com/zaproxy/zaproxy/issues/30).

I think OWASP ZAP can be added to the "Built with Kaitai Struct" section of Kaitai Struct's website. I can create a PR if needed.

Thanks.

**Comment by SkypLabs** [comment]
Hi @GreyCat. I'm just following up on this issue given the lack of responses.

**Comment by GreyCat** [comment]
Hey @SkypLabs, sorry about missing your previous message and thanks for the ping. Sure, absolutely go ahead and create a PR — it's great to raise awareness.

**Comment by SkypLabs** [comment]
Great, thanks.

Here's the PR: https://github.com/kaitai-io/kaitai-io.github.io/pull/24.

**Comment by generalmimon** [comment]
PR https://github.com/kaitai-io/kaitai-io.github.io/pull/24 has been merged, so this issue is resolved.
